baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Tien Trung'

theme = 'hugo-theme-relearn'

# Multilingual

defaultContentLanguage = 'en'

[languages]
    [languages.en]
        languageCode = 'en'
        languageName = 'English'
        title = 'Tien Trung'
        weight = 1

    [languages.vn]
        languageCode = 'vn'
        languageName = 'Vietnamese'
        title = 'Tiến Trung'
        weight = 1

[params]
    [params.author]
        email = 'trung.nt.e@gmail.com'
        name = 'Trung Nguyen-Tien'